# Data Arguments
DataArguments:
  dataset_name: ./data/aistage-mrc/train_dataset
  overwrite_cache: True
  preprocessing_num_workers: null
  max_seq_length: 384
  pad_to_max_length: False
  doc_stride: 128
  max_answer_length: 30
  eval_retrieval: True
  num_clusters: 64
  top_k_retrieval: 1
  use_faiss: True

# TrainingArguments:
NewTrainingArguments:
  # trainer_class: QuestionAnsweringTrainer
  report_to: wandb
  run_name: punc_5_0.2
  output_dir: outputs
  overwrite_output_dir: False
  learning_rate: 3e-5
  do_train: True
  do_eval: True
  do_predict: True # eval_retrieval = True 필수
  evaluation_strategy: epoch
  save_strategy: epoch
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  num_train_epochs: 10
  # eval_steps: 100
  # save_steps: 100
  save_total_limit: 1
  fp16: True
  weight_decay: 0.01
  warmup_steps: 100
  load_best_model_at_end: True
  metric_for_best_model: exact_match
  logging_dir: logs
  lr_scheduler_type: linear

# Model Arguments
ModelingArguments:
  model_name_or_path: klue/bert-base
  architectures: BertForQuestionAnswering
  method: ext
  config_name: null
  tokenizer_name: null
  model_cache_dir: cache
  model_init: basic
  
# Project Arguments
ProjectArguments:
  task: mrc
  wandb_project: jg_aeda_test
  save_model_dir: best
  checkpoint: None